#include "curl.h"

VALUE mCurl;

void Init_curl() {
	mCurl = rb_define_module("Curl");

	RUBY_CURL_DEF_CONST(CURLOPT_URL);
	RUBY_CURL_DEF_CONST(CURLOPT_POST);
	RUBY_CURL_DEF_CONST(CURLOPT_TIMEOUT);
	RUBY_CURL_DEF_CONST(CURLOPT_PUT);
	RUBY_CURL_DEF_CONST(CURLOPT_HTTPGET);
	RUBY_CURL_DEF_CONST(CURLOPT_UPLOAD);
	RUBY_CURL_DEF_CONST(CURLOPT_VERBOSE);
	RUBY_CURL_DEF_CONST(CURLOPT_POSTFIELDS);

	init_easy();
}
